### ISSUE TITLE
Request: Alt text in the carousel

### ISSUE THREAD

**Issue by bammerlaan** [cadamini/cadamini.github.io#22]
Hi Christian,

I came across your [page on adding links to the image carousel from jekyllcodex.org](https://adamini-online.de/test-images-carousel/) and it was really useful. I was wondering if I could make a request, because I want something slightly different. I would like to add an alt-text, or perhaps a caption on top of each photo. (I want to credit the photographers there.)

I'm really not proficient enough in the relevant coding required to do it myself, though... Is this something you could help me out with?

**Comment by cadamini** [comment]
Hi Sebastiaan, 

Sure thing, let me try. Happy to support you. The HTML in my example uses the object attributes for each image defined in the front matter.  I think you can modify the code as follows, for example.

**Updated Front matter with additional alt and caption texts:**

```
carousels:
- images: 
  - image: /assets/images/image-1.jpg
    url: post-name-1
    alt: "A beautiful sunrise over the mountains"
    caption: "Photo by John Doe"
  - image: /assets/images/image-2.jpg
    url: post-name-2
    alt: "City skyline at dusk"
    caption: "Photo by Jane Smith"
  - image: /assets/images/image-3.jpg
    url: post-name-3
    alt: "A peaceful lake surrounded by trees"
    caption: "Photo by Alex Johnson"
```

**This example HTML uses `item.alt` and `item.caption` attributes of the `item` object:**

(`images` is an array of objects, where each object (item) contains properties like image, url, alt, and caption now)

```
<div class="carousel__track">
  <ul>
    {% for item in page.carousels[number].images %}
      <li class="carousel__slide" style="background-image: url('{{ item.image }}');">
        <a href="{{ item.url }}" style="text-decoration:none;display:block;width:100%;height:100%;" 
           aria-label="{{ item.alt }}">
        </a>
        <div class="carousel__caption">{{ item.caption }}</div>
      </li>
    {% endfor %}
  </ul>
</div>
```

**With CSS, you can customize the look and feel, for example like this:**

```
.carousel__caption {
  position: absolute;
  bottom: 10px;
  left: 50%;
  transform: translateX(-50%);
  background: rgba(0, 0, 0, 0.6);
  color: white;
  padding: 5px 10px;
  font-size: 14px;
  border-radius: 5px;
}
```

If this does not help, you should dive into the official Jekyll docs, as well as HMTL and CSS references.

You have a really nice website, by the way. Good luck! Let me know if this was helpful already.

Best, 
Christian

P.S. I will not change my article for now. Maybe if you confirm that it was helpful. 

(Therefore tagged as help-wanted)
